In [1]:
import numpy as np

In [75]:
tica_proj = np.load('setd8_distances_tica_projection.npy', encoding='bytes')

In [5]:
tica_proj[0][0]

array([-0.99118072,  0.48661378,  1.54325569,  1.17640829,  1.09864092,
        1.10740554,  0.49807277,  1.00209963, -0.56032187,  0.18726696,
        0.32782957,  0.27118024, -0.46661445, -0.83517402,  0.38221055,
       -0.40340757, -0.18864483, -0.15883383, -0.5593242 , -0.53010172,
       -0.97360635,  0.68469584, -0.43244186,  0.01712857, -0.58563268,
       -0.05924939, -1.35284877,  0.61691749, -0.42424807, -0.32804725,
       -0.41952968,  0.4769592 , -0.8277337 , -0.15700063,  0.00195759,
        1.13215613,  0.16365153, -0.11906364,  0.41899833,  0.3528339 ,
        0.60738462,  0.46824899,  0.01219967,  0.24337849, -0.09522793,
        0.08890697, -0.00319768, -0.88888288,  0.21138351, -0.59520888], dtype=float32)

In [2]:
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

In [76]:
tic0_ = [x[:,0] for x in tica_proj]
tic1_ = [x[:,1] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y)        

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.savefig('tica/tics_0_1_normed_to_sum_1.png', dpi=300)
plt.close()

In [36]:
pwd

'/Users/rafalpwiewiora/repos/MSM/11707_11709_SET8_apo/msm_pipeline/dist'

In [54]:
tic0_ = [x[:,0] for x in tica_proj]
tic1_ = [x[:,1] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y)        

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100)
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.savefig('tica/tics_0_1_not_normed.png', dpi=300)
plt.close()

In [65]:
tic0_ = [x[:,0] for x in tica_proj]
tic1_ = [x[:,1] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y)        

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm())
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.savefig('tica/tics_0_1_not_normed_log10.png', dpi=300)
plt.close()

In [66]:
tic0_ = [x[:,0] for x in tica_proj]
tic1_ = [x[:,1] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y)        

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.savefig('tica/tics_0_1_normed_to_sum_1_log10.png', dpi=300)
plt.close()

ok these look great - now let's mark 3 things on that plot:

* actual starting points of the trajectories we are analyzing here (because we have cutoff the start a bit)
* starting points of the uncut trajectories
* homology models from the original structures (so that all atoms are there and we calculate the tICs)

In [67]:
# ok so let's see how many distinct starting points of the cut trajectories we have

In [73]:
cut_start_frames = []

for traj in tica_proj:
    cut_start_frames.append(traj[0,:2])

In [75]:
len(cut_start_frames)

3400

In [78]:
cut_start_frames_tic0 = []
cut_start_frames_tic1 = []

for x in cut_start_frames:
    cut_start_frames_tic0.append(x[0])
    cut_start_frames_tic1.append(x[1])

In [76]:
# now plot these as scatter in red on the histogram

In [82]:
tic0_ = [x[:,0] for x in tica_proj]
tic1_ = [x[:,1] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y)        

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.scatter(cut_start_frames_tic0, cut_start_frames_tic1, c='red', s=1)
plt.savefig('tica/tics_0_1_normed_to_sum_1_log10_cut_start_points_scatter.png', dpi=300)
plt.close()

In [83]:
# also plot those on the linear scale histogram

In [84]:
tic0_ = [x[:,0] for x in tica_proj]
tic1_ = [x[:,1] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y)        

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.scatter(cut_start_frames_tic0, cut_start_frames_tic1, c='red', s=1)
plt.savefig('tica/tics_0_1_normed_to_sum_1_cut_start_points_scatter.png', dpi=300)
plt.close()

In [85]:
# ok let's calculate out the other two cases - gotta recalculate the tICA is the problem - ok let's do this on the hal

In [86]:
# ok so let's try sampling along the tics

In [87]:
import msmbuilder

In [88]:
from msmbuilder.io.sampling import sample_dimension

In [90]:
help(sample_dimension)

Help on function sample_dimension in module msmbuilder.io.sampling.sampling:

sample_dimension(trajs, dimension, n_frames, scheme='linear')
    Sample a dimension of the data.
    
    This method uses one of 3 schemes. All other dimensions are ignored, so
    this might result in a really "jumpy" sampled trajectory.
    
    Parameters
    ----------
    trajs : dictionary of np.ndarray
        Dictionary of tica-transformed trajectories, keyed by arbitrary keys.
        The resulting trajectory indices will use these keys.
    dimension : int
        dimension to sample on
    n_frames : int
        Number of frames requested
    scheme : {'linear', 'random', 'edges'}
        'linear' samples the tic linearly, 'random' samples randomly
        (thereby taking approximate free energies into account),
        and 'edges' samples the edges of the tic only.
    
    Returns
    -------
    inds : list of tuples
       Tuples of (trajectory_index, frame_index), where trajectory_index is
 

In [94]:
tica_dict = dict()

for i in range(len(tica_proj)):
    tica_dict[i] = tica_proj[i]

In [96]:
samples_tic0_linear = sample_dimension(tica_dict, dimension=0, n_frames=50, scheme='linear')

In [97]:
samples_tic0_random = sample_dimension(tica_dict, dimension=0, n_frames=50, scheme='random')

In [135]:
samples_tic0_linear = [np.asarray(samples_tic0_linear)]

In [136]:
samples_tic0_random = [np.asarray(samples_tic0_random)]

In [137]:
np.save('samples_tic0_linear', samples_tic0_linear)

In [138]:
np.save('samples_tic0_random', samples_tic0_random)

In [103]:
samples_tic1_linear = sample_dimension(tica_dict, dimension=1, n_frames=50, scheme='linear')

In [104]:
samples_tic1_random = sample_dimension(tica_dict, dimension=1, n_frames=50, scheme='random')

In [139]:
samples_tic1_linear = [np.asarray(samples_tic1_linear)]

In [140]:
samples_tic1_random = [np.asarray(samples_tic1_random)]

In [141]:
np.save('samples_tic1_linear', samples_tic1_linear)

In [142]:
np.save('samples_tic1_random', samples_tic1_random)

In [143]:
samples_tic1_linear

[array([[1587, 1037],
        [1587, 1042],
        [1647,  182],
        [2233,  902],
        [ 131, 1141],
        [1746, 1328],
        [ 450, 1829],
        [1425,  243],
        [1683,  232],
        [ 637, 1718],
        [  76,  575],
        [2231,  627],
        [2347, 1234],
        [ 341,  635],
        [ 104, 1725],
        [2220, 1824],
        [1935, 1765],
        [ 120, 1179],
        [3235, 1190],
        [1607, 1532],
        [3217,  609],
        [2693, 1293],
        [2701, 1408],
        [2647, 1684],
        [3014, 1608],
        [ 102, 1591],
        [ 876,  603],
        [1603,  604],
        [2771, 1405],
        [3048, 1792],
        [ 751, 1484],
        [2784,  349],
        [2920, 1855],
        [2596, 1532],
        [  26,  497],
        [1278, 1821],
        [1285,  705],
        [3199, 1870],
        [1239, 1581],
        [ 539,  727],
        [ 208, 1676],
        [2059, 1537],
        [1269,  875],
        [ 451, 1365],
        [1063, 1516],
        [1

In [107]:
# retrieve frames on hal and have a look in pymol

In [108]:
# but before - let's retrieve those from the tica_proj and plot on the histogram - see how that sampling is distributed

In [115]:
tic0_linear = []
tic0_random = []
tic1_linear = []
tic1_random = []

for frame in samples_tic0_linear:
    tic0_linear.append(tica_proj[frame[0]][frame[1], :2])
for frame in samples_tic0_random:
    tic0_random.append(tica_proj[frame[0]][frame[1], :2]) 
for frame in samples_tic1_linear:
    tic1_linear.append(tica_proj[frame[0]][frame[1], :2])
for frame in samples_tic1_random:
    tic1_random.append(tica_proj[frame[0]][frame[1], :2])    

In [127]:
tic0_ = [x[:,0] for x in tica_proj]
tic1_ = [x[:,1] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y)        

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.scatter([x[0] for x in tic0_linear], [x[1] for x in tic0_linear], c=range(len(tic0_linear)), s=1, cmap='gist_rainbow')
plt.colorbar()
plt.savefig('tica/tic0_linear_50samples.png', dpi=300)
plt.close()

In [130]:
tic0_ = [x[:,0] for x in tica_proj]
tic1_ = [x[:,1] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y)        

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.scatter([x[0] for x in tic0_random], [x[1] for x in tic0_random], c=range(len(tic0_random)), s=1, cmap='gist_rainbow')
plt.colorbar()
plt.savefig('tica/tic0_random_50samples.png', dpi=300)
plt.close()

In [129]:
tic0_ = [x[:,0] for x in tica_proj]
tic1_ = [x[:,1] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y)        

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.scatter([x[0] for x in tic1_linear], [x[1] for x in tic1_linear], c=range(len(tic1_linear)), s=1, cmap='gist_rainbow')
plt.colorbar()
plt.savefig('tica/tic1_linear_50samples.png', dpi=300)
plt.close()

In [131]:
tic0_ = [x[:,0] for x in tica_proj]
tic1_ = [x[:,1] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y)        

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.scatter([x[0] for x in tic1_random], [x[1] for x in tic1_random], c=range(len(tic1_random)), s=1, cmap='gist_rainbow')
plt.colorbar()
plt.savefig('tica/tic1_random_50samples.png', dpi=300)
plt.close()

In [132]:
# ok let's take the samples to hal for sampling

In [133]:
pwd

'/Users/rafalpwiewiora/repos/MSM/11707_11709_SET8_apo/msm_pipeline/dist'

In [134]:
samples_tic1_linear

[(1587, 1037),
 (1587, 1042),
 (1647, 182),
 (2233, 902),
 (131, 1141),
 (1746, 1328),
 (450, 1829),
 (1425, 243),
 (1683, 232),
 (637, 1718),
 (76, 575),
 (2231, 627),
 (2347, 1234),
 (341, 635),
 (104, 1725),
 (2220, 1824),
 (1935, 1765),
 (120, 1179),
 (3235, 1190),
 (1607, 1532),
 (3217, 609),
 (2693, 1293),
 (2701, 1408),
 (2647, 1684),
 (3014, 1608),
 (102, 1591),
 (876, 603),
 (1603, 604),
 (2771, 1405),
 (3048, 1792),
 (751, 1484),
 (2784, 349),
 (2920, 1855),
 (2596, 1532),
 (26, 497),
 (1278, 1821),
 (1285, 705),
 (3199, 1870),
 (1239, 1581),
 (539, 727),
 (208, 1676),
 (2059, 1537),
 (1269, 875),
 (451, 1365),
 (1063, 1516),
 (1510, 744),
 (200, 9),
 (600, 148),
 (1703, 771),
 (1257, 299)]

In [144]:
# alright so this is promising - but waiting to re-calculate stuff on hal to tell for sure

In [145]:
# for now try another thing - let's see what kind of paths our trajectories trace on the 2D projection -
# maybe we can choose some to view

In [6]:
tic0_ = [x[:,0] for x in tica_proj]
tic1_ = [x[:,1] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y)  

In [169]:
traj_ = tica_proj[13]      

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.plot(traj_[:,0], traj_[:,1], color='red')
plt.savefig('tica/trajectory13.png', dpi=300)
plt.close()

In [ ]:
interesting_i = []

for i in range(len(tica_proj)):
    traj = tica_proj[i]
    for frame in traj:
        if frame[0] > -0.5 and frame[0] < 0.5:
            interesting_i.append(i)
            break

In [172]:
for i in interesting_i:

    traj_ = tica_proj[i]      

    plt.figure()
    plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
    plt.xlabel('tIC0')
    plt.ylabel('tIC1')
    plt.colorbar()
    plt.plot(traj_[:,0], traj_[:,1], color='red')
    plt.savefig('tica/trajs/trajectory%d.png' % i, dpi=300)
    plt.close()

In [164]:
interesting_i

[13,
 31,
 45,
 49,
 58,
 59,
 69,
 72,
 97,
 114,
 116,
 144,
 160,
 183,
 186,
 187,
 188,
 189,
 212,
 216,
 234,
 242,
 243,
 245,
 256,
 258,
 275,
 289,
 298,
 337,
 346,
 365,
 375,
 411,
 427,
 428,
 435,
 438,
 440,
 452,
 454,
 459,
 465,
 466,
 472,
 482,
 484,
 499,
 501,
 512,
 514,
 515,
 529,
 555,
 558,
 559,
 566,
 576,
 582,
 626,
 631,
 637,
 647,
 649,
 652,
 658,
 660,
 662,
 664,
 665,
 667,
 668,
 679,
 680,
 689,
 694,
 700,
 704,
 713,
 719,
 738,
 767,
 785,
 787,
 824,
 831,
 841,
 850,
 852,
 857,
 867,
 900,
 918,
 923,
 934,
 938,
 944,
 967,
 975,
 978,
 988,
 996,
 997,
 1000,
 1002,
 1004,
 1019,
 1036,
 1042,
 1044,
 1062,
 1069,
 1078,
 1080,
 1113,
 1114,
 1143,
 1183,
 1188,
 1189,
 1190,
 1192,
 1195,
 1201,
 1214,
 1248,
 1268,
 1273,
 1325,
 1350,
 1379,
 1406,
 1409,
 1412,
 1413,
 1414,
 1447,
 1454,
 1461,
 1473,
 1474,
 1508,
 1510,
 1529,
 1535,
 1541,
 1546,
 1642,
 1651,
 1666,
 1678,
 1685,
 1686,
 1690,
 1697,
 1707,
 1722,
 1724,
 1725,

In [165]:
len(interesting_i)

294

In [ ]:
# trajs to see - 13, 1036, 484, 514 !!, 515, 58, 582, 658, 665, 667, 700, 704, 852, 988, 1113, 1183, 1325, 1412, 1474, 
# 1690, 1749, 1984, 1989, 2106, 2187, 2303, 2430, 2849, 3037, 3348 || 2108 (! ?), 2187, 2430

In [173]:
# ok let's look at trajectory 514 - that was a pretty much full crossing

In [174]:
# plot it in 1D first

In [175]:
plt.figure()
plt.plot(tica_proj[514][:,0])
plt.xlabel('Time (0.5 ns/frame)')
plt.ylabel('tIC0')
plt.savefig('tica/traj514_tic0.png', dpi=300)

In [176]:
# '11707/run16-clone22.h5'

In [177]:
# ok so that looks pretty good - let's see the same idea for tic1 - pick trajectories which have crossed the -0.5 -
# i.e such that have both tic1 > -0.5 and < 0.5

In [7]:
interesting_i2 = []

for i in range(len(tica_proj)):
    traj = tica_proj[i]
    minus = False
    plus = False
    for frame in traj:
        if frame[1] > -0.5:
            minus = True
        elif frame[1] < 0.5:
            plus = True
        if minus and plus:
            interesting_i2.append(i)
            break    

In [8]:
len(interesting_i2)

731

In [9]:
# plot all

In [10]:
for i in interesting_i2:

    traj_ = tica_proj[i]      

    plt.figure()
    plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
    plt.xlabel('tIC0')
    plt.ylabel('tIC1')
    plt.colorbar()
    plt.plot(traj_[:,0], traj_[:,1], color='red')
    plt.savefig('tica/trajs_tic1/trajectory%d.png' % i, dpi=300)
    plt.close()

In [ ]:
# trajs to look at: 1115, 1139, 115, 1255, 1412, 28, 2808, 3192, 420, 875, 932

In [11]:
# ok let's look at 1115 first

In [ ]:
# '11707/run10-cloneo2.h5'

In [12]:
# plot in 1D

In [15]:
plt.figure()
plt.plot(tica_proj[1115][:,1])
plt.xlabel('Time (0.5 ns/frame)')
plt.ylabel('tIC1')
plt.savefig('tica/traj1115_tic1.png', dpi=300)

In [16]:
# check two more - 115 and 2808

In [17]:
plt.figure()
plt.plot(tica_proj[115][:,1])
plt.xlabel('Time (0.5 ns/frame)')
plt.ylabel('tIC1')
plt.savefig('tica/traj115_tic1.png', dpi=300)

In [18]:
plt.figure()
plt.plot(tica_proj[2808][:,1])
plt.xlabel('Time (0.5 ns/frame)')
plt.ylabel('tIC1')
plt.savefig('tica/traj2808_tic1.png', dpi=300)

In [19]:
# 115 is '11707/run25-clone10.h5'

In [20]:
# 2808 is '11709/run3-clone148.h5'

In [21]:
# use 1115 and 115 for presentation
# later try to explain why 2808 doesn't make much sense - there's not much changing about C-flank actually - 
# tic! might not be what I'm thinking it is

In [22]:
# alright going to hal now where we have a ready tica - 

# first - analyze eigenvectors - pick up the most important distances for tic0 and tic1

# then let's see if we can map the eq. starting points and the
# starting models onto the tic0tic1 space

# next thing - map 2500 microstates onto the tic0tic1 projection, then map macrostates, then - simulation from MSM
# and transition path theory - and we're done I think

In [23]:
pwd

'/Users/rafalpwiewiora/repos/MSM/11707_11709_SET8_apo/msm_pipeline/dist'

In [24]:
# let's look at eigenvectors

In [175]:
eigenvec = np.load('tica/tica_eigenvectors.npy')

In [176]:
eigenvec.shape

(1000, 1000)

In [27]:
# ok let's plot first and second eigenvectors

In [177]:
plt.figure()
plt.plot(eigenvec[:,0])
plt.xlabel('Distance index')
plt.ylabel('tic0 eiqenvector')
plt.savefig('tica/tic0_eigenvector.png', dpi=300)
plt.close()

In [178]:
plt.figure()
plt.plot(eigenvec[:,1])
plt.xlabel('Distance index')
plt.ylabel('tic1 eiqenvector')
plt.savefig('tica/tic1_eigenvector.png', dpi=300)
plt.close()

In [31]:
# tic0 eigenvect much more messy, tic1 pretty nice looking - let's look at the maximum and minimum for both

In [179]:
np.argmax(eigenvec[:,0])

1

In [181]:
np.argmin(eigenvec[:,0])

72

In [182]:
np.argmax(eigenvec[:,1])

39

In [183]:
np.argmin(eigenvec[:,1])

156

In [38]:
# let's check indexes of atoms

In [39]:
distances = np.load('tica/respairs_that_changed.npy')

In [43]:
distances[624]

array([110, 159])

In [47]:
distances[530]

array([ 79, 104])

In [48]:
distances[868]

array([73, 96])

In [49]:
distances[881]

array([ 9, 16])

In [50]:
import mdtraj as md

In [52]:
protein = md.load('tica/protein.pdb')

In [53]:
protein.top.residue(110)

LYS111

In [54]:
protein.top.residue(159)

LEU160

In [55]:
# alright - this is not making too much sense right now - investigate more later - for now forget about it

In [56]:
# move onto mapping the starting points onto the surface

In [58]:
# let's make a trajectory of all those points - and then analyze that as an MD trajectory through PyEMMA

In [59]:
# next - plot cluster centers - 2500 on the 2D surface - load cluster centers

In [60]:
cluster_centers_2500 = np.load('unitime_cluster/2500/clustercenters.npy')

In [63]:
cluster_centers_2500[:,:2]

array([[-1.0848254 ,  0.35427675],
       [-0.89869517,  0.16464229],
       [-1.11272502, -0.40577567],
       ..., 
       [ 0.99799603,  0.60049927],
       [ 1.07237053,  0.62969416],
       [ 1.08507586,  0.5722664 ]], dtype=float32)

In [64]:
# ok plot this

In [66]:
plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.scatter(cluster_centers_2500[:,0], cluster_centers_2500[:,1], c='red', s=1)
plt.savefig('tica/cluster_centers_2500.png', dpi=300)
plt.close()

In [67]:
# let's try 5000 just out of curiosity

In [68]:
cluster_centers_5000 = np.load('unitime_cluster/5000/clustercenters.npy')

In [69]:
plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.scatter(cluster_centers_5000[:,0], cluster_centers_5000[:,1], c='red', s=1)
plt.savefig('tica/cluster_centers_5000.png', dpi=300)
plt.close()

In [70]:
# ok cool - now let's plot the microstates in different colors, depending on macrostate

In [71]:
# I had those meta_sets saved for the rmsd analysis, the info is there!

In [74]:
# actually no - meta_sets is frame indexes, I gotta go back to that notebook and recover microstate in each macrostate
# list

In [75]:
metastable_micro_composition_2500 = np.load('unitime_cluster/2500/metastable_micro_composition.npy')

In [78]:
# ok so we have 2500 microstates - we're gonna pass a c of length 2500 to the scatter plotter, so let's get 
# a palette of 20 colors from iwanthue
# actually need 21 colors - 21st for those microstates which were thrown away to ergodicity
# intense - 20 colors

In [81]:
colors = ["#d16a52",
"#5d3ac7",
"#5cb845",
"#c34ddb",
"#b2ab36",
"#5a6acf",
"#db7426",
"#702f8d",
"#7baa6b",
"#d447a6",
"#52aca0",
"#d43636",
"#6290bf",
"#b2874d",
"#b684d8",
"#425b2b",
"#c1416f",
"#593c6b",
"#d0888c",
"#73332c",
"#c385b3"]

In [82]:
colors2 = []

for i in range(2500):
    done = False
    for j in range(20):
        if i in metastable_micro_composition_2500[j]:
            colors2.append(colors[j])
            done = True
    if not done:
        colors2.append(colors[20])

In [84]:
len(colors2)

2500

In [85]:
# ok let's plot

In [86]:
plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.scatter(cluster_centers_2500[:,0], cluster_centers_2500[:,1], c=colors2, s=1)
plt.savefig('tica/cluster_centers_2500_by_macrostate.png', dpi=300)
plt.close()

In [87]:
# nah can't see anything on this - let's make 20 plots

In [175]:
for i in range(20):
    macrostate = metastable_micro_composition_2500[i]
    
    x = []
    y = []

    for microstate in macrostate:
        x.append(cluster_centers_2500[microstate,0])
        y.append(cluster_centers_2500[microstate,1])
    
    plt.figure()
    plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
    plt.xlabel('tIC0')
    plt.ylabel('tIC1')
    plt.colorbar()
    plt.scatter(x, y, c='red')
    plt.title('Macrostate %d' % i)
    plt.savefig('tica/cluster_centers_by_macrostate/%d.png' % i, dpi=300)
    plt.close()

In [91]:
# make list of microstates that were thrown away to ergodicity

In [92]:
all_microstates = range(2500)

microstates_trashed = []

for i in all_microstates:
    not_trash = False
    for macrostate in metastable_micro_composition_2500:
        if i in macrostate:
            not_trash = True
            break
    if not not_trash:
        microstates_trashed.append(i)
    

In [94]:
len(microstates_trashed)

343

In [99]:
macrostate = microstates_trashed
    
x = []
y = []

for microstate in macrostate:
    x.append(cluster_centers_2500[microstate,0])
    y.append(cluster_centers_2500[microstate,1])
    
plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.scatter(x, y, c='red', s=2)
plt.title('Microstates rejected by ergodicity trimming')
plt.savefig('tica/cluster_centers_by_macrostate/not_in_macrostate.png', dpi=300)
plt.close()

In [98]:
# alright - we're gonna change to looking at the MSM now, particularly macrostate 19 looks interesting - 
# let's look for trajectories where we're in macrostate 19 for a long time

In [101]:
# ok - we're gonna plot only the models - not the equilibrated stuff - we have all points after equilibration and
# then another 'equilibration' (what we cut off) 

In [102]:
# we got the models, let's make one trajectory of those - take that to cluster and calculate the tic positions

In [103]:
import mdtraj as md

In [105]:
apo = md.load('tica/starting_structures/apo/model.pdb')
zkk = md.load('tica/starting_structures/1zkk/model.pdb')
ij8 = md.load('tica/starting_structures/4ij8/model.pdb')
inh = md.load('tica/starting_structures/inh/model.pdb')
zkk_apo = md.load('tica/starting_structures/1zkk_apo/model.pdb')
ij8_apo = md.load('tica/starting_structures/4ij8_apo/model.pdb')

In [107]:
traj = apo
traj = traj.join(zkk)
traj = traj.join(ij8)
traj = traj.join(inh)
traj = traj.join(zkk_apo)
traj = traj.join(ij8_apo)

In [108]:
traj

<mdtraj.Trajectory with 6 frames, 1296 atoms, 162 residues, without unitcells at 0x17e0aaba8>

In [109]:
traj.save('tica/starting_structures/all_traj.h5')

In [110]:
initial_conformations_tica = np.load('tica/starting_structures/initial_conformations_tica.npy')

In [111]:
# let's plot

In [113]:
initial_conformations_tica = initial_conformations_tica[0]

In [115]:
plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.scatter(initial_conformations_tica[:,0], initial_conformations_tica[:,1], c='red')
plt.savefig('tica/initial_conformations_on_tic01.png', dpi=300)
plt.close()

In [116]:
# good stuff!

In [168]:
initial_conformations_tica[0][:2] #apo

array([ 1.02063024, -1.29294705], dtype=float32)

In [169]:
initial_conformations_tica[1][:2] #zkk

array([-0.91809404,  0.49194032], dtype=float32)

In [170]:
initial_conformations_tica[2][:2] #ij8

array([ 0.94444132,  1.39091325], dtype=float32)

In [171]:
initial_conformations_tica[3][:2] #inh

array([-1.08758795, -0.10935054], dtype=float32)

In [172]:
initial_conformations_tica[4][:2] #zkk_apo

array([-0.86092108, -0.25153083], dtype=float32)

In [173]:
initial_conformations_tica[5][:2] #ij8_apo

array([ 0.95809561,  0.287853  ], dtype=float32)

In [117]:
# ok now let's look for trajectories where we spend a lot of time in macrostate 19
# then transition path theory - find max flux and visualize
# make more of the slides
# simulate for like 100 microseconds from the MSM - visualize changing of macrostates and 

In [118]:
# ok so let's load in dtrajs for 2500, convert them from microstate to macrostate (21 for microstates removed)
# and look for trajectories that contain 19

In [120]:
dtrajs_2500 = np.load('unitime_cluster/2500/dtrajs.npy', encoding='bytes')

In [124]:
# let's make a microstate to macrostate dictionary

In [125]:
micro_macro_dict = dict()

for i in range(2500):
    for j in range(20):
        if i in metastable_micro_composition_2500[j]:
            micro_macro_dict[i] = j
    if i not in micro_macro_dict:
        micro_macro_dict[i] = 20 

In [127]:
dtrajs_2500_macro = []

for traj in dtrajs_2500:
    dtrajs_2500_macro.append([])
    for microstate in traj:
        dtrajs_2500_macro[-1].append(micro_macro_dict[microstate])

In [129]:
# alright - let's see how many trajs have 19 in it

In [130]:
count = 0

for traj in dtrajs_2500_macro:
    if 19 in traj:
        count += 1

In [131]:
count

1477

In [132]:
# let's find the one with most 19 in it

In [133]:
count_list = []

for traj in dtrajs_2500_macro:
    count = 0
    for frame in traj:
        if frame == 19:
            count +=1
    count_list.append(count)        

In [135]:
np.argmax(count_list)

18

In [136]:
# traj 18 - let's plot it to see what macrostates it explores

In [137]:
pwd

'/Users/rafalpwiewiora/repos/MSM/11707_11709_SET8_apo/msm_pipeline/dist'

In [139]:
plt.figure()
plt.plot(dtrajs_2500_macro[18])
plt.xlabel('Time (0.5 ns / frame)')
plt.ylabel('Macrostate')
plt.savefig('tica/traj18_macro.png', dpi=300)
plt.close()

In [140]:
# there's no other macrostate here though - maybe find one where there is change?

In [141]:
count_list = []

for traj in dtrajs_2500_macro:
    count = [0,0]
    for frame in traj:
        if frame == 19:
            count[0] +=1
        elif frame != 19:
            count[1] += 1
    count_list.append(count)        

In [142]:
len(count_list)

3400

In [143]:
count = 0
for x in count_list:
    if x[0] > 0 and x[1] > 0:
        count += 1

In [144]:
count

1105

In [146]:
a = []

for x in count_list:
    if x[0] > 0 and x[1] > 0:
        a.append(x[0])

In [148]:
np.max(a)

2049

In [159]:
for i in range(3400):
    traj_count = count_list[i]
    if traj_count[0] > 1000 and traj_count[0] < 2000 and traj_count[1] > 0 and traj_count[1] < 250:
        print((i, traj_count[0], traj_count[1]))

(49, 1954, 6)
(50, 1904, 56)
(57, 1958, 2)
(62, 1884, 166)
(193, 1641, 139)
(204, 1982, 68)
(207, 1989, 61)
(269, 1883, 167)
(300, 1957, 3)
(301, 1935, 25)
(321, 1951, 9)
(388, 1936, 24)
(408, 1898, 152)
(417, 1960, 90)
(470, 1947, 13)
(471, 1955, 5)
(514, 1917, 43)
(515, 1911, 49)
(519, 1838, 212)
(523, 1936, 24)
(527, 1998, 52)
(536, 1953, 6)
(559, 1917, 43)
(562, 1992, 58)
(568, 1867, 183)
(595, 1869, 181)
(597, 1946, 14)
(620, 1957, 3)
(647, 1992, 58)
(664, 1833, 127)
(683, 1958, 2)
(691, 1992, 58)
(704, 1840, 210)
(745, 1937, 23)
(746, 1952, 98)
(750, 1997, 53)
(751, 1896, 64)
(800, 1951, 9)
(822, 1958, 2)
(848, 1958, 2)
(990, 1911, 49)
(1023, 1951, 99)
(1035, 1995, 55)
(1037, 1991, 59)
(1039, 1877, 173)
(1095, 1959, 1)
(1111, 1977, 73)
(1121, 1959, 91)
(1159, 1617, 133)
(1178, 1967, 83)
(1206, 1994, 56)
(1232, 1996, 54)
(1233, 1915, 135)
(1235, 1822, 138)
(1238, 1884, 76)
(1255, 1973, 17)
(1300, 1871, 179)
(1320, 1893, 67)
(1324, 1960, 90)
(1409, 1914, 136)
(1422, 1783, 177)
(147

In [160]:
# (1751, 1810, 240)

In [161]:
# traj 1751 is: '11707/run10-clone21.h5'

In [162]:
# plot the traj

In [163]:
plt.figure()
plt.plot(dtrajs_2500_macro[1751])
plt.xlabel('Time (0.5 ns / frame)')
plt.ylabel('Macrostate')
plt.savefig('tica/traj1751_macro.png', dpi=300)
plt.close()

In [164]:
# also plot this traj in tica space

In [165]:
# then - TPT and we should be really finally done, put the story again, sleep

In [166]:
traj_ = tica_proj[1751]      

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.plot(traj_[:,0], traj_[:,1], color='red')
plt.savefig('tica/trajs_msm/traj1751_tica.png', dpi=300)
plt.close()

In [174]:
# not sure about usefulness of this 
# next and last - transition path theory - let's do it in the actual MSM notebook 

In [ ]:
# alright let's do top flux into 1ZKK-like macrostates from any others, 

In [176]:
# not doing the tpt after all - just doing a 100 microsecond simulation from the MSM - all done here, just gonna
# simulate and sample in dist_2500_unitime

In [177]:
# coming here back with samples from a 300 microsecond simulation from the MSM - plot onto the tIC0-tIC1

In [178]:
pwd

'/Users/rafalpwiewiora/repos/MSM/11707_11709_SET8_apo/msm_pipeline/dist'

In [179]:
samples_simulation = np.load('tica/samples_simulation.npy')

In [180]:
samples_simulation[0]

array([[1235,  632]])

In [182]:
# ok so just look through tica_proj to find the coordinates

In [196]:
simulation_tica = []

for frame in samples_simulation:
    simulation_tica.append(tica_proj[frame[0,0]][frame[0,1]][:2])

In [195]:
samples_simulation[0,0,1]

632

In [198]:
len(simulation_tica)

2000

In [200]:
simulation_tica[0]

array([ 0.99091154,  1.16856623], dtype=float32)

In [199]:
# ok awesome - let's plot this

In [201]:
plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC1')
plt.colorbar()
plt.plot([x[0] for x in simulation_tica], [x[1] for x in simulation_tica], color='red')
plt.savefig('tica/simulation_tica.png', dpi=300)
plt.close()

In [1]:
# back here May 5th - two things to do: plot starting structures on all combinations of tic0 and tic1 with tics2-9; 
# examine tica eigenvectors further - make structural intepretation

In [2]:
# start with eigenvectors

In [184]:
eigenvec = np.load('tica/tica_eigenvectors.npy')

In [7]:
distances = np.load('tica/respairs_that_changed.npy')

In [9]:
pwd

'/Users/rafalpwiewiora/repos/MSM/11707_11709_SET8_apo/msm_pipeline/dist'

In [10]:
# let's plot all 50 tics vs distance index
# and let's also look at these 1000 distances - which regions are they in between?

In [185]:
for i in range(50):
    plt.figure()
    plt.plot(eigenvec[:,i])
    plt.xlabel('Distance index')
    plt.ylabel('tic%s eiqenvector' % i)
    plt.savefig('tica/eigenv/tic%s.png' % i, dpi=300)
    plt.close()

In [12]:
distances[0]

array([ 16, 121])

In [13]:
# let's make a 2D figure 161 x 161 imshow, have ones where there is a distance we consider, zero where there isn't

In [14]:
# then can mark the distances important for particular tics on that chart

In [26]:
distances_matrix = np.zeros((162, 162))

In [27]:
for x in distances:
    distances_matrix[x[0], x[1]] = 1
    distances_matrix[x[1], x[0]] = 1

In [28]:
plt.figure()
plt.imshow(distances_matrix, cmap='Blues')
plt.savefig('tica/1000dist.png', dpi=300)
plt.close()

In [30]:
# ok that looks good - now look at tic0 and tic1 and take top some number of distances - plot on the imshow to see
# what they are between - analyze most promising ones in Pymol

In [33]:
# tic0 - let's take all distances above 1 and below -1

In [34]:
tic0_distances = []

for i in range(1000):
    if eigenvec[0][i] > 1 or eigenvec[0][i] < -1:
        tic0_distances.append(i)

In [43]:
plt.figure()
plt.imshow(distances_matrix, cmap='Blues')
for x in tic0_distances:
    plt.scatter(distances[x][0], distances[x][1], c='red')
plt.savefig('tica/tic0_dist.png', dpi=300)
plt.close()

In [46]:
tic1_distances = []

for i in range(1000):
    if eigenvec[1][i] > 2 or eigenvec[1][i] < -2:
        tic1_distances.append(i)

In [47]:
plt.figure()
plt.imshow(distances_matrix, cmap='Blues')
for x in tic1_distances:
    plt.scatter(distances[x][0], distances[x][1], c='red')
plt.savefig('tica/tic1_dist.png', dpi=300)
plt.close()

In [48]:
tic2_distances = []

for i in range(1000):
    if eigenvec[2][i] > 2 or eigenvec[2][i] < -2:
        tic2_distances.append(i)

In [49]:
plt.figure()
plt.imshow(distances_matrix, cmap='Blues')
for x in tic2_distances:
    plt.scatter(distances[x][0], distances[x][1], c='red')
plt.savefig('tica/tic2_dist.png', dpi=300)
plt.close()

In [50]:
tic3_distances = []

for i in range(1000):
    if eigenvec[3][i] > 2 or eigenvec[3][i] < -2:
        tic3_distances.append(i)

In [51]:
plt.figure()
plt.imshow(distances_matrix, cmap='Blues')
for x in tic3_distances:
    plt.scatter(distances[x][0], distances[x][1], c='red')
plt.savefig('tica/tic3_dist.png', dpi=300)
plt.close()

In [54]:
tic4_distances = []

for i in range(1000):
    if eigenvec[4][i] > 1 or eigenvec[4][i] < -1:
        tic4_distances.append(i)

In [55]:
plt.figure()
plt.imshow(distances_matrix, cmap='Blues')
for x in tic4_distances:
    plt.scatter(distances[x][0], distances[x][1], c='red')
plt.savefig('tica/tic4_dist.png', dpi=300)
plt.close()

In [56]:
# ok let's have a look in Pymol - tic0 first

In [58]:
tic0_distances = []

for i in range(1000):
    if eigenvec[0][i] > 1 or eigenvec[0][i] < -1:
        tic0_distances.append(i)
        
tic0_distances_resindex = []

for x in tic0_distances:
    tic0_distances_resindex.append(distances[x])

In [59]:
tic0_distances_resindex

[array([ 7, 12]),
 array([ 80, 107]),
 array([157, 161]),
 array([ 80, 108]),
 array([148, 159]),
 array([57, 97]),
 array([111, 133]),
 array([ 71, 158]),
 array([63, 67]),
 array([67, 97]),
 array([59, 91]),
 array([73, 83]),
 array([54, 95]),
 array([ 90, 152]),
 array([115, 148]),
 array([ 71, 149]),
 array([100, 104]),
 array([113, 133]),
 array([18, 21]),
 array([ 26, 141]),
 array([74, 81]),
 array([ 82, 116]),
 array([ 77, 107]),
 array([145, 156]),
 array([ 7, 14]),
 array([ 79, 104]),
 array([0, 3]),
 array([147, 153]),
 array([129, 141]),
 array([ 68, 156]),
 array([ 90, 154]),
 array([72, 79]),
 array([3, 9]),
 array([ 68, 157]),
 array([ 47, 132]),
 array([  4, 122]),
 array([ 12, 117]),
 array([  8, 120]),
 array([ 65, 158]),
 array([110, 159]),
 array([ 4, 49]),
 array([ 90, 157]),
 array([37, 77]),
 array([ 2, 16]),
 array([ 3, 11]),
 array([ 2, 20]),
 array([108, 153]),
 array([ 65, 155]),
 array([ 0, 10]),
 array([15, 19]),
 array([23, 26]),
 array([ 86, 125]),
 array

In [60]:
len(tic0_distances_resindex)

65

In [61]:
tic0_distances_resindex_toanalyze = []

for x in tic0_distances_resindex:
    if (x[0] >= 59 and x[0] <= 94 and x[1] >= 145) or (x[1] >= 59 and x[1] <= 94 and x[0] >= 145):
        tic0_distances_resindex_toanalyze.append(x)

In [62]:
len(tic0_distances_resindex_toanalyze)

11

In [63]:
tic0_distances_resindex_toanalyze

[array([ 71, 158]),
 array([ 90, 152]),
 array([ 71, 149]),
 array([ 68, 156]),
 array([ 90, 154]),
 array([ 68, 157]),
 array([ 65, 158]),
 array([ 90, 157]),
 array([ 65, 155]),
 array([ 67, 155]),
 array([ 83, 147])]

In [64]:
# now same for tic1

In [69]:
tic1_distances = []

for i in range(1000):
    if eigenvec[1][i] > 2 or eigenvec[1][i] < -2:
        tic1_distances.append(i)
        
tic1_distances_resindex = []

for x in tic1_distances:
    tic1_distances_resindex.append(distances[x])

In [70]:
tic1_distances_resindex_toanalyze = []

for x in tic1_distances_resindex:
    if (x[0] >= 59 and x[0] <= 94 and x[1] >= 145) or (x[1] >= 59 and x[1] <= 94 and x[0] >= 145):
        tic1_distances_resindex_toanalyze.append(x)

In [71]:
len(tic1_distances_resindex_toanalyze)

7

In [73]:
tic1_distances_resindex_toanalyze

[array([ 68, 160]),
 array([ 71, 160]),
 array([ 84, 156]),
 array([ 90, 161]),
 array([ 77, 158]),
 array([ 88, 157]),
 array([ 68, 161])]

In [74]:
# alright last thing now - plot starting structures on more tics

In [77]:
initial_conformations_tica = np.load('tica/starting_structures/initial_conformations_tica.npy')

In [88]:
initial_conformations_tica = initial_conformations_tica[0]

In [89]:
tic0_ = [x[:,0] for x in tica_proj]
tic1_ = [x[:,2] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y) 

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC2')
plt.colorbar()
plt.scatter(initial_conformations_tica[:,0], initial_conformations_tica[:,2], c='red')
plt.savefig('tica/initial_conformations_on_tic02.png', dpi=300)
plt.close()

In [90]:
tic0_ = [x[:,0] for x in tica_proj]
tic1_ = [x[:,3] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y) 

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC3')
plt.colorbar()
plt.scatter(initial_conformations_tica[:,0], initial_conformations_tica[:,3], c='red')
plt.savefig('tica/initial_conformations_on_tic03.png', dpi=300)
plt.close()

In [91]:
tic0_ = [x[:,0] for x in tica_proj]
tic1_ = [x[:,4] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y) 

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC4')
plt.colorbar()
plt.scatter(initial_conformations_tica[:,0], initial_conformations_tica[:,4], c='red')
plt.savefig('tica/initial_conformations_on_tic04.png', dpi=300)
plt.close()

In [92]:
tic0_ = [x[:,1] for x in tica_proj]
tic1_ = [x[:,2] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y) 

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC1')
plt.ylabel('tIC2')
plt.colorbar()
plt.scatter(initial_conformations_tica[:,1], initial_conformations_tica[:,2], c='red')
plt.savefig('tica/initial_conformations_on_tic12.png', dpi=300)
plt.close()

In [93]:
tic0_ = [x[:,1] for x in tica_proj]
tic1_ = [x[:,3] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y) 

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC1')
plt.ylabel('tIC3')
plt.colorbar()
plt.scatter(initial_conformations_tica[:,1], initial_conformations_tica[:,3], c='red')
plt.savefig('tica/initial_conformations_on_tic13.png', dpi=300)
plt.close()

In [94]:
tic0_ = [x[:,1] for x in tica_proj]
tic1_ = [x[:,4] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y) 

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC1')
plt.ylabel('tIC4')
plt.colorbar()
plt.scatter(initial_conformations_tica[:,1], initial_conformations_tica[:,4], c='red')
plt.savefig('tica/initial_conformations_on_tic14.png', dpi=300)
plt.close()

In [96]:
# back here - we have sparse tica calculating on the cluster - let's plot all 2D combinations of tics 0-9, with starting
# structures

# then plot distances colored by eigenvector weight for tics 0-9

In [98]:
# also we have sparse tica done - look at the eigenvectors - actually not yet, the eigenvectors take a while
# back to the above

In [99]:
initial_conformations_tica = np.load('tica/starting_structures/initial_conformations_tica.npy')
initial_conformations_tica = initial_conformations_tica[0]

In [108]:
tic0_ = [x[:,0] for x in tica_proj]
tic1_ = [x[:,2] for x in tica_proj]

tic0 = []
tic1 = []

for x in tic0_:
    for y in x:
        tic0.append(y)
for x in tic1_:
    for y in x:
        tic1.append(y) 

plt.figure()
plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
plt.xlabel('tIC0')
plt.ylabel('tIC2')
plt.colorbar()
plt.scatter(initial_conformations_tica[0,0], initial_conformations_tica[0,2], marker='o', c='red')
plt.scatter(initial_conformations_tica[1,0], initial_conformations_tica[1,2], marker='x', c='red')
plt.scatter(initial_conformations_tica[2,0], initial_conformations_tica[2,2], marker='*', c='red')
plt.scatter(initial_conformations_tica[3,0], initial_conformations_tica[3,2], marker='s', c='red')
plt.scatter(initial_conformations_tica[4,0], initial_conformations_tica[4,2], marker='^', c='red')
plt.scatter(initial_conformations_tica[5,0], initial_conformations_tica[5,2], marker='+', c = 'red')
plt.savefig('tica/initial_conformations_on_test.png', dpi=300)
plt.close()

In [ ]:
# test works good - let's do this for all combinations of tics 0-9

In [132]:
import itertools

In [137]:
combinations = itertools.combinations(range(10),2)

In [139]:
combinations = itertools.combinations(range(10),2)

for (i,j) in combinations:
    tic0_ = [x[:,i] for x in tica_proj]
    tic1_ = [x[:,j] for x in tica_proj]

    tic0 = []
    tic1 = []

    for x in tic0_:
        for y in x:
            tic0.append(y)
    for x in tic1_:
        for y in x:
            tic1.append(y) 

    plt.figure()
    plt.hist2d(tic0, tic1, cmap='Blues', bins=100, norm=matplotlib.colors.LogNorm(), weights=[1/len(tic0)]*len(tic0))
    plt.xlabel('tIC%d' % i)
    plt.ylabel('tIC%d' % j)
    plt.colorbar()
    plt.scatter(initial_conformations_tica[0,i], initial_conformations_tica[0,j], marker='o', c='red')
    plt.scatter(initial_conformations_tica[1,i], initial_conformations_tica[1,j], marker='x', c='red')
    plt.scatter(initial_conformations_tica[2,i], initial_conformations_tica[2,j], marker='*', c='red')
    plt.scatter(initial_conformations_tica[3,i], initial_conformations_tica[3,j], marker='s', c='red')
    plt.scatter(initial_conformations_tica[4,i], initial_conformations_tica[4,j], marker='^', c='red')
    plt.scatter(initial_conformations_tica[5,i], initial_conformations_tica[5,j], marker='+', c = 'red')
    plt.savefig('tica/2d_tics_initial_conf/tic%d-tic%d.png' % (i,j), dpi=300)
    plt.close()

In [109]:
# look at the sparse eigenvectors

In [110]:
sparse_eigenv = np.load('tica/sparse_eigenvectors.npy')

In [116]:
sparse_eigenv2 = np.transpose(sparse_eigenv)

In [117]:
sparse_eigenv2.shape

(50, 1000)

In [118]:
for i in range(50):
    plt.figure()
    plt.plot(sparse_eigenv2[i])
    plt.xlabel('Distance index')
    plt.ylabel('tic%s eiqenvector' % i)
    plt.savefig('tica/sparse_eigenv/tic%s.png' % i, dpi=300)
    plt.close()

In [ ]:
# ok this is a bit weird - doesn't match with the pyemma tica - let's run msmbuilder normal tica on this X and compare

In [140]:
# ok got the eigenvectors for msmbuilder tica - let's plot and compare

In [142]:
#plt.figure()
#plt.scatter(initial_conformations_tica[0,i], initial_conformations_tica[0,j], marker='o', c='red')
#plt.scatter(initial_conformations_tica[1,i], initial_conformations_tica[1,j], marker='x', c='red')
#plt.scatter(initial_conformations_tica[2,i], initial_conformations_tica[2,j], marker='*', c='red')
#plt.scatter(initial_conformations_tica[3,i], initial_conformations_tica[3,j], marker='s', c='red')
#plt.scatter(initial_conformations_tica[4,i], initial_conformations_tica[4,j], marker='^', c='red')
#plt.scatter(initial_conformations_tica[5,i], initial_conformations_tica[5,j], marker='+', c = 'red')
#plt.savefig('tica/2d_tics_initial_conf/test.png', dpi=300)
#plt.close()

In [143]:
# load and plot normal tiCA eigenvectors from msmbuilder

In [144]:
msmb_eigenv = np.load('tica/eigenvectors_msmbuilder.npy')

In [145]:
msmb_eigenv2 = np.transpose(msmb_eigenv)

In [147]:
msmb_eigenv2.shape

(50, 1000)

In [148]:
for i in range(50):
    plt.figure()
    plt.plot(msmb_eigenv2[i])
    plt.xlabel('Distance index')
    plt.ylabel('tic%s eiqenvector' % i)
    plt.savefig('tica/msmb_eigenv/tic%s.png' % i, dpi=300)
    plt.close()

In [149]:
# ok so we have a total disagreement between eigenvectors from PyEMMA and MSMBuilder tica - let's re-do both here 
# on the freshest code versions

In [150]:
import pyemma
import msmbuilder

In [152]:
X = list(np.load('X.npy', encoding='bytes'))

In [153]:
tica_pyemma = pyemma.coordinates.tica(X, lag=50, kinetic_map=True, dim=50)

In [154]:
from msmbuilder import decomposition

In [155]:
tica_msmbuilder = msmbuilder.decomposition.tICA(n_components=50, lag_time=50, kinetic_mapping=True)

In [163]:
tica_msmbuilder.fit(X)

/Users/rafalpwiewiora/anaconda3/lib/python3.5/site-packages/msmbuilder/decomposition/tica.py:405: UserWarning: The number of features (550) is greater than the length of the data (1000). The covariance matrix is not guaranteed to be positive definite.
  warnings.warn("The number of features (%d) is greater than the length of the data (%d). The covariance matrix is not guaranteed to be positive definite." % (X.shape[0], X.shape[1]))
/Users/rafalpwiewiora/anaconda3/lib/python3.5/site-packages/msmbuilder/decomposition/tica.py:405: UserWarning: The number of features (939) is greater than the length of the data (1000). The covariance matrix is not guaranteed to be positive definite.
  warnings.warn("The number of features (%d) is greater than the length of the data (%d). The covariance matrix is not guaranteed to be positive definite." % (X.shape[0], X.shape[1]))
/Users/rafalpwiewiora/anaconda3/lib/python3.5/site-packages/msmbuilder/decomposition/tica.py:405: UserWarning: The number of fea

tICA(commute_mapping=False, kinetic_mapping=True, lag_time=50,
   n_components=50, shrinkage=None)

In [164]:
tica_pyemma_eigenv = tica_pyemma.eigenvectors

In [167]:
tica_pyemma_eigenv.shape

(1000, 1000)

In [168]:
tica_msmbuilder_eigenv = tica_msmbuilder.eigenvectors_

In [169]:
tica_msmbuilder_eigenv.shape

(1000, 50)

In [170]:
plt.figure()
plt.plot(tica_pyemma_eigenv[:, 0])
plt.savefig('tica/debug/tica_pyemma_0.png')

In [171]:
plt.figure()
plt.plot(tica_msmbuilder_eigenv[:, 0])
plt.savefig('tica/debug/tica_msmbuilder_0.png')

In [172]:
plt.figure()
plt.plot(tica_pyemma_eigenv[0, :])
plt.savefig('tica/debug/tica_pyemma_0_.png')

In [173]:
# ok mystery solved - I was plotting THE WRONG AXIS

In [174]:
del X

In [186]:
# ok so everything agrees - and any of the distance intepretations before WERE WRONG

In [187]:
# ok so first - make new intepretations of tic0 and tic1 - look in pymol - then move onto sparse
# also do distances colored by tics - now we have the right ones

In [188]:
# distances - 50 tics - colored by weight for normal tica
# distances - 50 tics - red marked the distances in tics

In [189]:
# then we can do analysis of tic0 and tic1 for both normal and sparse tica

In [190]:
# alright - let's do distances - colored by tica coeff

In [3]:
distances = np.load('tica/respairs_that_changed.npy')

distances_matrix = np.zeros((162, 162))

for x in distances:
    distances_matrix[x[0], x[1]] = 1
    distances_matrix[x[1], x[0]] = 1

In [4]:
distances_matrix

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [79]:
plt.figure()
plt.imshow(np.log(distances_matrix), cmap='gray')
plt.xticks(np.arange(0, 180, 20))
plt.yticks(np.arange(0, 180, 20))
plt.savefig('tica/1000dist.png', dpi=300)
plt.close()

/Users/rafalpwiewiora/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in log
  from ipykernel import kernelapp as app


In [6]:
# now we want to make a new distances_matrix_by_tic0 and _by_tic1 which will not have 1/0, but weights from the 
# tica eigenvectors

In [10]:
msmb_eigenv = np.load('tica/eigenvectors_msmbuilder.npy')
msmb_eigenv = np.transpose(msmb_eigenv)

In [14]:
msmb_eigenv.shape

(50, 1000)

In [15]:
distances_matrix_by_tic0 = np.zeros((162, 162))
distances_matrix_ = distances_matrix_by_tic0
tic = 0

for i in range(1000):
    x = distances[i]
    distances_matrix_[x[0], x[1]] = msmb_eigenv[tic, i]
    distances_matrix_[x[1], x[0]] = msmb_eigenv[tic, i]

In [18]:
# great - plot

In [34]:
np.max(distances_matrix_by_tic0)

0.30828768291441905

In [35]:
np.min(distances_matrix_by_tic0)

-0.26293093727356776

In [77]:
plt.figure()
plt.imshow(distances_matrix_by_tic0, cmap='seismic', vmin=-np.max(distances_matrix_by_tic0), vmax=np.max(distances_matrix_by_tic0))
plt.colorbar()
plt.xticks(np.arange(0, 180, 20))
plt.yticks(np.arange(0, 180, 20))
plt.savefig('tica/1000dist_by_tic0.png', dpi=300)
plt.close()

In [78]:
plt.figure()
plt.imshow(np.log10(np.absolute(distances_matrix_by_tic0)), cmap='Blues')
plt.colorbar()
plt.xticks(np.arange(0, 180, 20))
plt.yticks(np.arange(0, 180, 20))
plt.savefig('tica/1000dist_by_tic0_abs_log10.png', dpi=300)
plt.close()

/Users/rafalpwiewiora/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in log10
  from ipykernel import kernelapp as app


In [81]:
# ok this works great! let's do this for all 50 tics 
# next - same thing for sparse tica
# next - print out the indexes of residues for all 50 tics from sparse
# then put that all on drive, send to shi
# then - movies along tics - 0 and 1 - send to shi already, then make up to tic9
# then - my analysis of the tics

In [85]:
for j in range(50):
    tic = j
    
    distances_matrix_by_tic0 = np.zeros((162, 162))
    distances_matrix_ = distances_matrix_by_tic0

    for i in range(1000):
        x = distances[i]
        distances_matrix_[x[0], x[1]] = msmb_eigenv[tic, i]
        distances_matrix_[x[1], x[0]] = msmb_eigenv[tic, i]
        
    if np.abs(np.max(distances_matrix_)) > np.abs(np.min(distances_matrix_)):
        vmin = -np.max(distances_matrix_)
        vmax = np.max(distances_matrix_)
    else:
        vmin = np.min(distances_matrix_)
        vmax = -np.min(distances_matrix_)
    
    plt.figure()
    plt.imshow(distances_matrix_by_tic0, cmap='seismic', vmin=vmin, vmax=vmax)
    plt.colorbar()
    plt.xticks(np.arange(0, 180, 20))
    plt.yticks(np.arange(0, 180, 20))
    plt.savefig('tica/tica_eig_dist/1000dist_by_tic%d.png' % j, dpi=300)
    plt.close()
    
    plt.figure()
    plt.imshow(np.log10(np.absolute(distances_matrix_by_tic0)), cmap='Blues')
    plt.colorbar()
    plt.xticks(np.arange(0, 180, 20))
    plt.yticks(np.arange(0, 180, 20))
    plt.savefig('tica/tica_eig_dist/1000dist_by_tic%d_abs_log10.png' % j, dpi=300)
    plt.close()

/Users/rafalpwiewiora/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:28: RuntimeWarning: divide by zero encountered in log10


In [86]:
# ok this is great - now do this for sparse

In [87]:
sparse_eigenv = np.load('tica/sparse_eigenvectors.npy')
sparse_eigenv = np.transpose(sparse_eigenv)

In [89]:
for j in range(50):
    tic = j
    
    distances_matrix_by_tic0 = np.zeros((162, 162))
    distances_matrix_ = distances_matrix_by_tic0

    for i in range(1000):
        x = distances[i]
        distances_matrix_[x[0], x[1]] = sparse_eigenv[tic, i]
        distances_matrix_[x[1], x[0]] = sparse_eigenv[tic, i]
        
    if np.abs(np.max(distances_matrix_)) > np.abs(np.min(distances_matrix_)):
        vmin = -np.max(distances_matrix_)
        vmax = np.max(distances_matrix_)
    else:
        vmin = np.min(distances_matrix_)
        vmax = -np.min(distances_matrix_)
    
    plt.figure()
    plt.imshow(distances_matrix_by_tic0, cmap='seismic', vmin=vmin, vmax=vmax)
    plt.colorbar()
    plt.xticks(np.arange(0, 180, 20))
    plt.yticks(np.arange(0, 180, 20))
    plt.savefig('tica/sparse_tica_eig_dist/1000dist_by_tic%d.png' % j, dpi=300)
    plt.close()
    
    plt.figure()
    plt.imshow(np.log10(np.absolute(distances_matrix_by_tic0)), cmap='Blues')
    plt.colorbar()
    plt.xticks(np.arange(0, 180, 20))
    plt.yticks(np.arange(0, 180, 20))
    plt.savefig('tica/sparse_tica_eig_dist/1000dist_by_tic%d_abs_log10.png' % j, dpi=300)
    plt.close()

/Users/rafalpwiewiora/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:28: RuntimeWarning: divide by zero encountered in log10


In [99]:
# now we gotta assemble a list of lists of lists - residue pairs from sparse tica for all 50 tics
# WARNING - THEY WILL BE 1-INDEXED

In [110]:
residue_pairs = []

for j in range(50):
    residue_pairs.append([])
    tic = j
    
    for i in range(1000):
        if sparse_eigenv[tic, i] != 0:
            res1 = distances[i,0]
            res2 = distances[i,1]
            residue_pairs[-1].append(('%s-%d' % (sequence[res1], res1+1), '%s-%d' % (sequence[res2], res2+1), sparse_eigenv[tic, i]))

In [111]:
residue_pairs

[[('E-61', 'A-65', 0.72558439218976023),
  ('A-65', 'C-93', 0.4424227115925296),
  ('R-68', 'D-95', 0.50959075609701587),
  ('I-62', 'L-71', -0.38887214605377191),
  ('L-71', 'C-93', -0.48329125246336069)],
 [('Q-74', 'S-77', 0.91468575210665293),
  ('Q-86', 'S-153', -0.27068666567160121),
  ('Y-72', 'G-79', 0.50348733911489485),
  ('G-79', 'R-149', 0.46796757264925576),
  ('D-64', 'K-67', 0.90373810792371645),
  ('Y-72', 'Y-81', -0.57606560140500662),
  ('Y-81', 'G-147', -0.43373912685493193),
  ('Y-81', 'S-150', -0.35535692149762615),
  ('T-63', 'P-158', -0.16819483899955151),
  ('C-80', 'A-156', 0.2933158037083618)],
 [('D-17', 'H-120', -0.43840596903354939),
  ('G-147', 'K-151', 0.50104697752409366),
  ('Q-74', 'S-77', 0.68734252310632449),
  ('C-80', 'R-149', 0.82635317260815411),
  ('F-85', 'A-152', 0.40998132565271656),
  ('N-108', 'W-159', -0.2232732692476935),
  ('F-85', 'A-156', 0.39428312902672452),
  ('Y-81', 'G-147', -0.79565094092765398),
  ('Y-81', 'H-157', -0.4039132011

In [104]:
# ok so prepare movies for tic0 and 1 - put on Drive, and all the plots
# next - sampling and movies of tics 2 to 9
# then analyze distances from sparse

In [105]:
# let's add the AA symbols to those, and the value of the eigenvector weight

In [107]:
import mdtraj as md

In [108]:
sequence = md.load('tica/protein.pdb').top.to_fasta()[0]

In [109]:
sequence

'SRKSKAELQSEERKRIDELIESGKEEGMKIDLIDGKGRGVIATKQFSRGDFVVEYHGDLIEITDAKKREALYAQDPSTGCYMYYFQYLSKTYCVDATRETNRLGRLINHSKCGNCQTKLHDIDGVPHLILIASRDIAAGEELLYDYGDRSKASIEAHPWLKH'

In [112]:
# now make 191-indexed version for Shi

In [113]:
residue_pairs = []

for j in range(50):
    residue_pairs.append([])
    tic = j
    
    for i in range(1000):
        if sparse_eigenv[tic, i] != 0:
            res1 = distances[i,0]
            res2 = distances[i,1]
            residue_pairs[-1].append(('%s-%d' % (sequence[res1], res1+191), '%s-%d' % (sequence[res2], res2+191), sparse_eigenv[tic, i]))

In [114]:
residue_pairs

[[('E-251', 'A-255', 0.72558439218976023),
  ('A-255', 'C-283', 0.4424227115925296),
  ('R-258', 'D-285', 0.50959075609701587),
  ('I-252', 'L-261', -0.38887214605377191),
  ('L-261', 'C-283', -0.48329125246336069)],
 [('Q-264', 'S-267', 0.91468575210665293),
  ('Q-276', 'S-343', -0.27068666567160121),
  ('Y-262', 'G-269', 0.50348733911489485),
  ('G-269', 'R-339', 0.46796757264925576),
  ('D-254', 'K-257', 0.90373810792371645),
  ('Y-262', 'Y-271', -0.57606560140500662),
  ('Y-271', 'G-337', -0.43373912685493193),
  ('Y-271', 'S-340', -0.35535692149762615),
  ('T-253', 'P-348', -0.16819483899955151),
  ('C-270', 'A-346', 0.2933158037083618)],
 [('D-207', 'H-310', -0.43840596903354939),
  ('G-337', 'K-341', 0.50104697752409366),
  ('Q-264', 'S-267', 0.68734252310632449),
  ('C-270', 'R-339', 0.82635317260815411),
  ('F-275', 'A-342', 0.40998132565271656),
  ('N-298', 'W-349', -0.2232732692476935),
  ('F-275', 'A-346', 0.39428312902672452),
  ('Y-271', 'G-337', -0.79565094092765398),
  

In [116]:
# now wanna see if any of these residues repeat between tics, and how many times - let's make a grand dictionary of all

In [117]:
residue_pairs = []
residue_pairs_dict = dict()

for j in range(50):
    residue_pairs.append([])
    tic = j
    
    for i in range(1000):
        if sparse_eigenv[tic, i] != 0:
            res1 = distances[i,0]
            res2 = distances[i,1]
            residue_pairs[-1].append(('%s-%d' % (sequence[res1], res1+191), '%s-%d' % (sequence[res2], res2+191), sparse_eigenv[tic, i]))
            tuple_ = ('%s-%d' % (sequence[res1], res1+191), '%s-%d' % (sequence[res2], res2+191))
            if tuple_ in residue_pairs_dict:
                residue_pairs_dict[tuple_] += 1
            else:
                residue_pairs_dict[tuple_] = 1

In [118]:
residue_pairs_dict

{('A-196', 'E-201'): 1,
 ('A-196', 'R-205'): 4,
 ('A-255', 'C-283'): 1,
 ('A-255', 'E-259'): 6,
 ('A-255', 'R-258'): 6,
 ('A-255', 'W-349'): 4,
 ('A-255', 'Y-274'): 4,
 ('A-260', 'A-263'): 2,
 ('A-263', 'A-346'): 5,
 ('A-263', 'G-269'): 4,
 ('A-263', 'H-347'): 2,
 ('A-263', 'M-272'): 4,
 ('A-263', 'P-266'): 2,
 ('A-263', 'T-287'): 1,
 ('A-263', 'W-349'): 2,
 ('A-286', 'E-289'): 1,
 ('A-286', 'R-295'): 2,
 ('A-342', 'A-346'): 2,
 ('A-342', 'L-350'): 1,
 ('A-346', 'L-350'): 3,
 ('A-346', 'W-349'): 1,
 ('C-270', 'A-286'): 1,
 ('C-270', 'A-346'): 2,
 ('C-270', 'I-297'): 2,
 ('C-270', 'N-298'): 2,
 ('C-270', 'P-348'): 2,
 ('C-270', 'R-339'): 4,
 ('C-270', 'S-340'): 7,
 ('C-270', 'S-343'): 3,
 ('C-270', 'W-349'): 3,
 ('C-270', 'Y-273'): 3,
 ('C-270', 'Y-334'): 3,
 ('C-270', 'Y-336'): 6,
 ('C-305', 'D-335'): 3,
 ('C-305', 'R-324'): 1,
 ('D-207', 'E-211'): 2,
 ('D-207', 'H-310'): 3,
 ('D-207', 'I-312'): 1,
 ('D-254', 'K-257'): 5,
 ('D-254', 'R-258'): 3,
 ('D-265', 'C-270'): 1,
 ('D-265', 'G-26

In [121]:
sorted(residue_pairs_dict.items(), key = lambda x: x[1], reverse=True)

[(('D-311', 'V-315'), 24),
 (('R-203', 'E-211'), 16),
 (('S-194', 'E-197'), 13),
 (('I-297', 'Y-336'), 12),
 (('I-210', 'I-319'), 11),
 (('Y-271', 'G-337'), 11),
 (('S-200', 'K-204'), 10),
 (('R-203', 'D-311'), 10),
 (('Y-271', 'R-339'), 9),
 (('S-340', 'S-343'), 9),
 (('F-275', 'Y-336'), 9),
 (('E-259', 'R-339'), 8),
 (('I-252', 'I-344'), 8),
 (('T-307', 'D-338'), 8),
 (('T-268', 'I-297'), 8),
 (('H-246', 'G-294'), 7),
 (('Y-262', 'S-267'), 7),
 (('T-253', 'S-279'), 7),
 (('Y-336', 'S-340'), 7),
 (('S-267', 'C-270'), 7),
 (('G-213', 'R-292'), 7),
 (('R-339', 'A-342'), 7),
 (('D-265', 'T-268'), 7),
 (('R-203', 'D-207'), 7),
 (('C-270', 'S-340'), 7),
 (('I-252', 'L-261'), 6),
 (('G-269', 'Y-273'), 6),
 (('F-275', 'A-346'), 6),
 (('G-247', 'E-289'), 6),
 (('A-255', 'R-258'), 6),
 (('Y-271', 'S-340'), 6),
 (('A-255', 'E-259'), 6),
 (('H-299', 'D-338'), 6),
 (('I-206', 'F-241'), 6),
 (('D-338', 'A-342'), 6),
 (('Y-336', 'L-350'), 6),
 (('E-251', 'A-255'), 6),
 (('C-270', 'Y-336'), 6),
 (('

In [122]:
len(sorted(residue_pairs_dict.items(), key = lambda x: x[1], reverse=True))

449

In [123]:
# now rank individual residues

In [124]:
residue_pairs = []
residue_pairs_dict = dict()
residue_dict = dict()

for j in range(50):
    residue_pairs.append([])
    tic = j
    
    for i in range(1000):
        if sparse_eigenv[tic, i] != 0:
            res1 = distances[i,0]
            res2 = distances[i,1]
            residue_pairs[-1].append(('%s-%d' % (sequence[res1], res1+191), '%s-%d' % (sequence[res2], res2+191), sparse_eigenv[tic, i]))
            tuple_ = ('%s-%d' % (sequence[res1], res1+191), '%s-%d' % (sequence[res2], res2+191))
            if tuple_ in residue_pairs_dict:
                residue_pairs_dict[tuple_] += 1
            else:
                residue_pairs_dict[tuple_] = 1
            res1_string = '%s-%d' % (sequence[res1], res1+191)
            res2_string = '%s-%d' % (sequence[res2], res2+191)
            if res1_string in residue_dict:
                residue_dict[res1_string] += 1
            else:
                residue_dict[res1_string] = 1
            if res2_string in residue_dict:
                residue_dict[res2_string] += 1
            else:
                residue_dict[res2_string] = 1    

In [125]:
sorted(residue_dict.items(), key = lambda x: x[1], reverse=True)

[('Y-336', 91),
 ('R-339', 88),
 ('Y-271', 66),
 ('R-203', 60),
 ('C-270', 59),
 ('S-340', 58),
 ('Y-273', 51),
 ('W-349', 50),
 ('S-343', 49),
 ('F-275', 48),
 ('D-338', 47),
 ('Y-262', 47),
 ('L-350', 43),
 ('G-269', 41),
 ('H-347', 40),
 ('Y-274', 38),
 ('D-311', 38),
 ('I-344', 37),
 ('T-268', 37),
 ('D-265', 36),
 ('A-346', 36),
 ('I-252', 33),
 ('P-266', 33),
 ('R-258', 33),
 ('S-267', 32),
 ('M-272', 31),
 ('G-337', 30),
 ('I-206', 30),
 ('A-342', 28),
 ('A-255', 28),
 ('E-202', 28),
 ('I-297', 27),
 ('H-299', 27),
 ('H-246', 27),
 ('S-200', 26),
 ('I-210', 25),
 ('E-211', 25),
 ('A-263', 25),
 ('R-205', 25),
 ('E-259', 25),
 ('V-315', 24),
 ('D-207', 23),
 ('Q-264', 23),
 ('E-197', 23),
 ('R-292', 23),
 ('S-194', 22),
 ('Y-334', 22),
 ('T-307', 21),
 ('L-198', 20),
 ('I-319', 19),
 ('K-204', 19),
 ('R-192', 19),
 ('D-335', 18),
 ('E-289', 18),
 ('L-209', 18),
 ('K-341', 17),
 ('G-213', 17),
 ('L-309', 17),
 ('D-240', 17),
 ('E-201', 17),
 ('G-294', 16),
 ('P-348', 16),
 ('F-241